---
- name: netctl | Deploy interfaces
  template:
    src: "netctl.j2"
    dest: "{{ hostvars[inventory_hostname]['netctl_dest'] ~ '/' ~ item.interface }}"
    group: "root"
    owner: "root"
    force: "yes"
    mode: "0644"
  with_items: "{{ hostvars[inventory_hostname]['netctl_interfaces'] | json_query(\"[?interface=='\" + vars['outer_item'] + \"']\") }}"
  loop_control:
    label: "{{ item.interface }}"
  notify:
  - "Enable netctl profiles"
  - "Start netctl profiles"
