---
- name: netctl | Deploy netctl profiles
  template:
    src: "netctl.j2"
    dest: "{{ hostvars[inventory_hostname]['netctl_dest'] + '/' + item.interface }}"
    group: "root"
    owner: "root"
    mode: "0644"
  with_items: "{{ hostvars[inventory_hostname]['netctl'] }}"
  register: "netctl_deploy_result"
  notify:
  - "Enable netctl profiles"
  - "Start netctl profiles"
- name: netctl | Add kernel options for bonding
  template:
    src: "modprobe.j2"
    dest: "{{ hostvars[inventory_hostname]['netctl_modprobe_dest'] + '/' + 'bonding.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
  when:
  - "hostvars[inventory_hostname]['netctl_bonding'] is defined"
