---
- name: netctl | Deploy hooks
  template:
    src: "hooks.j2"
    dest: "{{ hostvars[inventory_hostname]['netctl_dest'] ~ '/' ~
              'hooks' ~ '/' ~ item.name }}"
    group: "root"
    owner: "root"
    force: "yes"
    mode: "0755"
  loop: "{{ hostvars[inventory_hostname]['netctl_hooks'] |
    json_query(\"[?name=='\" ~ vars['outer_item'] ~ \"']\") |
    flatten(levels=1) }}"
  loop_control:
    label: "{{ item.name }}"
