---
- include: pre_requisite.yml
- include: interface_executor.yml
  when:
  - "vars['network_interfaces'] is defined"
  - "hostvars[inventory_hostname]['netctl_deploy_interfaces'] is defined"
  - "hostvars[inventory_hostname]['netctl_deploy_interfaces'] == 'true'"
