---
- name: netctl | Add the OS specific variables
  include_vars: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: netctl | Set facts about interfaces
  set_fact:
    network_interfaces: "{{ hostvars[inventory_hostname]['netctl_interfaces'] | json_query('[].interface') }}"
  when:
  - "hostvars[inventory_hostname]['netctl_interfaces'] is defined"
  - "hostvars[inventory_hostname]['netctl_interfaces'] != ''"
- name: netctl | Find exists network profiles
  find:
    paths: "{{ hostvars[inventory_hostname]['netctl_dest'] + '/' + 'netctl' }}"
    recurse: "no"
    file_type: "file"
    patterns: "(.*)"
    use_regex: "true"
  register: "find_result"
  when:
  - "hostvars[inventory_hostname]['netctl_drop_exists'] is defined"
  - "hostvars[inventory_hostname]['netctl_drop_exists'] == 'true'"
- name: netctl | Delete exists network profiles
  file:
    path: "{{ item.path }}"
    state: "absent"
  with_items: "{{ vars['find_result']['files'] }}"
  loop_control:
    label: "{{ item.path }}"
  when:
  - "vars['find_result']['files'] is defined"
