---
- name: Enable netctl profiles
  command: "{{ 'netctl enable' ~ ' ' ~ item }}"
  loop: "{{ vars['network_interfaces'] | flatten(levels=1) }}"
  register: "enable_result"
  changed_when:
  - "enable_result is success"
  - "('already' not in enable_result.stderr and 'ln' in enable_result.stdout)"
  when:
  - "hostvars[inventory_hostname]['netctl_enable'] is defined"
  - "hostvars[inventory_hostname]['netctl_enable'] == 'true'"
- name: Start netctl profiles
  command: "{{ 'netctl start' ~ ' ' ~ item }}"
  loop: "{{ vars['network_interfaces'] | flatten(levels=1) }}"
  when:
  - "hostvars[inventory_hostname]['netctl_restart'] is defined"
  - "hostvars[inventory_hostname]['netctl_restart'] == 'true'"
