---
- name: Enable netctl profiles
  command: "{{ 'netctl enable' ~ ' ' ~ item }}"
  with_items: "{{ vars['network_interfaces'] }}"
  register: "enable_result"
  changed_when:
  - "enable_result|success"
  - "('already' not in enable_result.stderr and 'ln' in enable_result.stdout)"
  when:
  - "hostvars[inventory_hostname]['netctl_enable'] is defined"
  - "hostvars[inventory_hostname]['netctl_enable'] == 'true'"
- name: Start netctl profiles
  command: "{{ 'netctl start' ~ ' ' ~ item.interface }}"
  with_items: "{{ hostvars[inventory_hostname]['netctl'] }}"
  loop_control:
    label: "{{ item.interface }}"
  when:
  - "hostvars[inventory_hostname]['netctl_restart'] is defined"
  - "hostvars[inventory_hostname]['netctl_restart'] == 'true'"
